### ISSUE TITLE
vlfeat crash on specific machines

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/openMVG#76]
I get this crash on some machines of the renderfarm (always the same ones).

```
- EXTRACT FEATURES -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
Extracting features from image 25
SIFT description

Program received signal SIGILL, Illegal instruction.
0x000000000050bb07 in vl_sift_new ()
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-9.fc20.x86_64 expat-2.1.0-7.fc20.x86_64 fontconfig-2.11.0-2.fc20.x86_64 freetype-2.5.0-10.fc20.x86_64 glib2-2.38.2-2.fc20.x86_64 glibc-2.18-19.fc20.x86_64 jasper-libs-1.900.1-28.fc20.x86_64 jbigkit-libs-2.0-10.fc20.x86_64 libICE-1.0.8-6.fc20.x86_64 libSM-1.2.1-6.fc20.x86_64 libX11-1.6.1-1.fc20.x86_64 libXau-1.0.8-2.fc20.x86_64 libXcursor-1.1.14-2.fc20.x86_64 libXext-1.3.2-2.fc20.x86_64 libXfixes-5.0.1-2.fc20.x86_64 libXi-1.7.4-1.fc20.x86_64 libXinerama-1.1.3-2.fc20.x86_64 libXrandr-1.4.1-2.fc20.x86_64 libXrender-0.9.8-2.fc20.x86_64 libffi-3.0.13-5.fc20.x86_64 libjpeg-turbo-1.3.1-3.fc20.x86_64 libpng-1.6.6-3.fc20.x86_64 libpng12-1.2.50-6.fc20.x86_64 libuuid-2.24.2-2.fc20.x86_64 libxcb-1.9.1-3.fc20.x86_64 qt-4.8.6-25.fc20.x86_64 qt-x11-4.8.6-25.fc20.x86_64 xz-libs-5.1.2-12alpha.fc20.x86_64 zlib-1.2.8-3.fc20.x86_64
(gdb) bt
#0  0x000000000050bb07 in vl_sift_new ()
#1  0x0000000000491b54 in openMVG::features::SIFT_Image_describer::Describe(openMVG::image::Image<unsigned char> const&, std::unique_ptr<openMVG::features::Regions, std::default_delete<openMVG::features::Regions> >&, openMVG::image::Image<unsigned char> const*) ()
#2  0x00000000004cb0a1 in openMVG::features::SIFT_CCTAG_Image_describer::Describe(openMVG::image::Image<unsigned char> const&, std::unique_ptr<openMVG::features::Regions, std::default_delete<openMVG::features::Regions> >&, openMVG::image::Image<unsigned char> const*) ()
#3  0x0000000000478563 in main ()
```

**Comment by simogasp** [comment]
can u paste the command line?

**Comment by simogasp** [comment]
@fabiencastan still crashing?

**Comment by fabiencastan** [comment]
I think it's a problem of binary compatibility due to optimizations done on the compiled machine but not compatible with older hardware. So we can close the issue.

**Comment by zvrba** [comment]
It says SIGILL, so I think you're right: this is triggered when you run AVX or AVX2 code on a machine not supporting it.
